"""add fields to order

Revision ID: 029ddd7c55a1
Revises: 8152e2f1060a
Create Date: 2025-01-03 11:56:55.734863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '029ddd7c55a1'
down_revision: Union[str, None] = '8152e2f1060a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_option', sa.String(length=50), nullable=False))
    op.add_column('orders', sa.Column('time_taken', sa.String(length=50), nullable=False))
    op.add_column('orders', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'comment')
    op.drop_column('orders', 'time_taken')
    op.drop_column('orders', 'payment_option')
    # ### end Alembic commands ###
