"""add ingredient type

Revision ID: 0f38330194a0
Revises: 7d848b238e44
Create Date: 2025-05-28 01:03:04.934480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f38330194a0'
down_revision: Union[str, None] = '7d848b238e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'type')
    # ### end Alembic commands ###
