"""delete pk for category in product

Revision ID: 173ecf119ab3
Revises: e4b620d4e8dc
Create Date: 2025-05-11 20:12:30.311645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '173ecf119ab3'
down_revision: Union[str, None] = 'e4b620d4e8dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
