"""change tables for products and basket

Revision ID: 30053a7bbc44
Revises: 4adc2ca6bf67
Create Date: 2024-10-12 13:02:29.884206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30053a7bbc44'
down_revision: Union[str, None] = '4adc2ca6bf67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sizes',
    sa.Column('size_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('grams', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('size_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('baskets',
    sa.Column('basket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('basket_id')
    )
    op.create_table('prices',
    sa.Column('price_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['size_id'], ['sizes.size_id'], ),
    sa.PrimaryKeyConstraint('price_id')
    )
    op.create_table('basket_items',
    sa.Column('basket_item_id', sa.Integer(), nullable=False),
    sa.Column('basket_id', sa.Integer(), nullable=False),
    sa.Column('price_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.basket_id'], ),
    sa.ForeignKeyConstraint(['price_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('basket_item_id')
    )
    op.drop_table('basket')
    op.drop_column('products', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_table('basket',
    sa.Column('basket_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name='basket_product_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='basket_user_id_fkey'),
    sa.PrimaryKeyConstraint('basket_id', name='basket_pkey')
    )
    op.drop_table('basket_items')
    op.drop_table('prices')
    op.drop_table('baskets')
    op.drop_table('sizes')
    # ### end Alembic commands ###
