"""not unique

Revision ID: 45518b7179ef
Revises: 11c7f3214195
Create Date: 2025-06-10 01:38:09.538260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45518b7179ef'
down_revision: Union[str, None] = '11c7f3214195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sizes_name_key', 'sizes', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('sizes_name_key', 'sizes', ['name'])
    # ### end Alembic commands ###
