"""add basket_item_excluded_ingredients

Revision ID: 556a0be7da8a
Revises: b924e9807a60
Create Date: 2025-05-25 21:39:21.045410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '556a0be7da8a'
down_revision: Union[str, None] = 'b924e9807a60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basket_item_excluded_ingredients',
    sa.Column('basket_item_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['basket_item_id'], ['basket_items.basket_item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('basket_item_id', 'ingredient_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basket_item_excluded_ingredients')
    # ### end Alembic commands ###
