"""add grams for ingredient

Revision ID: 71ef45e4d673
Revises: 0f38330194a0
Create Date: 2025-05-29 08:30:02.144255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ef45e4d673'
down_revision: Union[str, None] = '0f38330194a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('grams', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'grams')
    # ### end Alembic commands ###
