"""add color

Revision ID: 99a17b14ec72
Revises: 173ecf119ab3
Create Date: 2025-05-19 21:23:37.257836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99a17b14ec72'
down_revision: Union[str, None] = '173ecf119ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'color')
    # ### end Alembic commands ###
