"""add params for price

Revision ID: a97a4d8476b7
Revises: e203bf36a6b8
Create Date: 2025-04-01 20:51:13.957612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a97a4d8476b7'
down_revision: Union[str, None] = 'e203bf36a6b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('proteins', sa.Integer(), nullable=True))
    op.add_column('prices', sa.Column('fats', sa.Integer(), nullable=True))
    op.add_column('prices', sa.Column('carbohydrates', sa.Integer(), nullable=True))
    op.add_column('prices', sa.Column('calories', sa.Integer(), nullable=True))
    op.add_column('prices', sa.Column('is_custom', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prices', 'is_custom')
    op.drop_column('prices', 'calories')
    op.drop_column('prices', 'carbohydrates')
    op.drop_column('prices', 'fats')
    op.drop_column('prices', 'proteins')
    # ### end Alembic commands ###
