"""delete ingredient comment

Revision ID: b924e9807a60
Revises: f86eb54d3341
Create Date: 2025-05-25 21:05:10.275456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b924e9807a60'
down_revision: Union[str, None] = 'f86eb54d3341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prices', 'ingredient_comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('ingredient_comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
