"""fix price_id in basket_item

Revision ID: c5a1ee4c6816
Revises: 55b312983f1f
Create Date: 2024-10-17 20:14:11.178954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a1ee4c6816'
down_revision: Union[str, None] = '55b312983f1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('basket_items_price_id_fkey', 'basket_items', type_='foreignkey')
    op.create_foreign_key(None, 'basket_items', 'prices', ['price_id'], ['price_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'basket_items', type_='foreignkey')
    op.create_foreign_key('basket_items_price_id_fkey', 'basket_items', 'users', ['price_id'], ['user_id'])
    # ### end Alembic commands ###
