"""basket model update

Revision ID: c8ca1f1ce46e
Revises: 140cda419305
Create Date: 2024-11-16 23:46:26.684605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8ca1f1ce46e'
down_revision: Union[str, None] = '140cda419305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('baskets_user_id_fkey', 'baskets', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('baskets_user_id_fkey', 'baskets', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
