"""discount

Revision ID: cb510355b1bd
Revises: e23f467cd66f
Create Date: 2025-06-26 13:26:17.809203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb510355b1bd'
down_revision: Union[str, None] = 'e23f467cd66f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baskets', sa.Column('discount', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('discount', sa.Float(), nullable=True))
    op.alter_column('users', 'coins',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'coins',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('orders', 'discount')
    op.drop_column('baskets', 'discount')
    # ### end Alembic commands ###
