"""add cascade delete

Revision ID: d499133a37fa
Revises: 029ddd7c55a1
Create Date: 2025-02-11 21:00:25.801310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd499133a37fa'
down_revision: Union[str, None] = '029ddd7c55a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('basket_items_basket_id_fkey', 'basket_items', type_='foreignkey')
    op.drop_constraint('basket_items_price_id_fkey', 'basket_items', type_='foreignkey')
    op.create_foreign_key(None, 'basket_items', 'prices', ['price_id'], ['price_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'basket_items', 'baskets', ['basket_id'], ['basket_id'], ondelete='CASCADE')
    op.drop_constraint('orders_basket_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'baskets', ['basket_id'], ['basket_id'], ondelete='CASCADE')
    op.drop_constraint('prices_size_id_fkey', 'prices', type_='foreignkey')
    op.drop_constraint('prices_product_id_fkey', 'prices', type_='foreignkey')
    op.create_foreign_key(None, 'prices', 'sizes', ['size_id'], ['size_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'prices', 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.drop_constraint('product_ingredient_ingredient_id_fkey', 'product_ingredient', type_='foreignkey')
    op.drop_constraint('product_ingredient_product_id_fkey', 'product_ingredient', type_='foreignkey')
    op.create_foreign_key(None, 'product_ingredient', 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'product_ingredient', 'ingredients', ['ingredient_id'], ['ingredient_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_ingredient', type_='foreignkey')
    op.drop_constraint(None, 'product_ingredient', type_='foreignkey')
    op.create_foreign_key('product_ingredient_product_id_fkey', 'product_ingredient', 'products', ['product_id'], ['product_id'])
    op.create_foreign_key('product_ingredient_ingredient_id_fkey', 'product_ingredient', 'ingredients', ['ingredient_id'], ['ingredient_id'])
    op.drop_constraint(None, 'prices', type_='foreignkey')
    op.drop_constraint(None, 'prices', type_='foreignkey')
    op.create_foreign_key('prices_product_id_fkey', 'prices', 'products', ['product_id'], ['product_id'])
    op.create_foreign_key('prices_size_id_fkey', 'prices', 'sizes', ['size_id'], ['size_id'])
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_basket_id_fkey', 'orders', 'baskets', ['basket_id'], ['basket_id'])
    op.drop_constraint(None, 'basket_items', type_='foreignkey')
    op.drop_constraint(None, 'basket_items', type_='foreignkey')
    op.create_foreign_key('basket_items_price_id_fkey', 'basket_items', 'prices', ['price_id'], ['price_id'])
    op.create_foreign_key('basket_items_basket_id_fkey', 'basket_items', 'baskets', ['basket_id'], ['basket_id'])
    # ### end Alembic commands ###
