"""add ingredient price

Revision ID: e203bf36a6b8
Revises: d847c75cca6f
Create Date: 2025-04-01 20:08:23.589187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e203bf36a6b8'
down_revision: Union[str, None] = 'd847c75cca6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'price')
    # ### end Alembic commands ###
