"""not unique product

Revision ID: e23f467cd66f
Revises: 45518b7179ef
Create Date: 2025-06-10 02:27:07.005198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e23f467cd66f'
down_revision: Union[str, None] = '45518b7179ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_name_key', 'products', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('products_name_key', 'products', ['name'])
    # ### end Alembic commands ###
