"""add fields to order

Revision ID: e7e79da950cb
Revises: 556a0be7da8a
Create Date: 2025-05-25 21:43:00.591845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7e79da950cb'
down_revision: Union[str, None] = '556a0be7da8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('address', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('phone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'phone')
    op.drop_column('orders', 'address')
    op.drop_column('orders', 'first_name')
    # ### end Alembic commands ###
