"""add ingredient_comment

Revision ID: f86eb54d3341
Revises: 99a17b14ec72
Create Date: 2025-05-22 20:19:55.192731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f86eb54d3341'
down_revision: Union[str, None] = '99a17b14ec72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('ingredient_comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prices', 'ingredient_comment')
    # ### end Alembic commands ###
